### ISSUE TITLE
Add support for JasperReport Server 6.4

### ISSUE THREAD

**Issue by NicoTexas** [TIBCOSoftware/js-docker#14]
Add support for JasperReport Server 6.4.

According to documentation, server install guide
JVM Options on Linux and Mac OSX
Options for all app servers,all JDKs
JAVA_OPTS="$JAVA_OPTS -Xms1024m -Xmx2048m -Xss2m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"

**Comment by nataliiakel** [comment]
@NicoTexas  we will add your request to roadmap.
