### ISSUE TITLE
Docker compose fail on windows 10

### ISSUE THREAD

**Issue by albertotn** [TIBCOSoftware/js-docker#16]
Steps to reproduce the problem:

1) use windows 10
2) clone the repository
3) cd js-docker
4) docker-compose

To get the following error:

> 
> js_database uses an image, skipping
> Building jasperserver
> Step 1/9 : FROM tomcat:8.0-jre8
> 8.0-jre8: Pulling from library/tomcat
> 3e731ddb7fc9: Pull complete
> 47cafa6a79d0: Pull complete
> 79fcf5a213c7: Pull complete
> fd532571c5d3: Pull complete
> 31600c9f9b48: Pull complete
> 78e8e9b5d10e: Pull complete
> 0710e619e883: Pull complete
> e511da65ffab: Pull complete
> bfcd79b5752d: Pull complete
> f6d4311e9998: Pull complete
> 2f7df330dbbc: Pull complete
> ccc1fcecb7e8: Pull complete
> Digest: sha256:d469ae288bc7bb1060948967e8f2b41f9927abf06b6c9fefad9fe4d9f2d1b1a6
> Status: Downloaded newer image for tomcat:8.0-jre8
>  ---> 7972d20e02cf
> Step 2/9 : COPY resources/jasperreports-server*zip /tmp/jasperserver.zip
> ERROR: Service 'jasperserver' failed to build: COPY failed: no source files were specified
>

**Comment by andrevasconcellos** [comment]
Hi. Have you downloaded the jasperreports-server file to the resources folder? The script is trying to copy this file from there to the temporary folder.

**Comment by albertotn** [comment]
You are right, thanks, totally missed this part.
In my mind was just simply run docker without config, need to read more carefully the prerequisite part!

**Comment by nataliiakel** [comment]
@andrevasconcellos Looks like issue is resolved and can be closed now. Please, reopen if anything else is needed.

**Comment by andrevasconcellos** [comment]
Hi!  I'm not sure why I've being cited here as I was just helping the other
user. oO

Em qui, 12 de abr de 2018 09:39, Natalia Keleberdenko <
notifications@github.com> escreveu:
