### ISSUE TITLE
issue related docker run with jasper 

### ISSUE THREAD

**Issue by bibinrcggs** [TIBCOSoftware/js-docker#18]
Hi,

i m trying to jasper community edition in my local system using docker run but getting this error 
"unzip:  cannot find or open ../jasperserver-pro.war, ../jasperserver-pro.war.zip or ../jasperserver-pro.war.ZIP."

i used command "docker run --name some-jasperserver -p 8282:8080 \
-e DB_HOST=jasper-rds-XXXXX -e DB_USER=XXXXX \
-e DB_PASSWORD=XXXXXXX -d jasperserver-pro:6.3.0"

please help me to fix it.

**Comment by aveiga** [comment]
I too am having the same issue. Somewhere in the JasperSoft community forums it's stated that this repo will work with the community edition. Is this true?

**Comment by dtelaroli** [comment]
The problem is on this [line](https://github.com/TIBCOSoftware/js-docker/blob/master/scripts/entrypoint.sh#L53)

The community version is _jasperserver.war_ against _jasperserver-pro.war_

**Comment by nataliiakel** [comment]
this edition is certified to work with professional edition.
