### ISSUE TITLE
Changing content of zip causes a permission failed

### ISSUE THREAD

**Issue by s133996** [TIBCOSoftware/js-docker#19]
I had a working version of this project, but whenver I try to change the contents of the zip file (the jasperreport server zip file)  I get the error: /entrypoint.sh: line 57: ./js-ant: Permission denied the first time and /entrypoint.sh: line 66: ./js-ant: Permission denied the second. (the lines being "init-source-paths \" and "./js-ant $i \" respectively)

 I want to change the js.quartz.properties file like in: https://community.jaspersoft.com/wiki/configuring-report-scheduler so that the dockerised server can send emails. 

doing that or just any change, like adding an empty .txt file or deleting a file in the zip folder will start making permission denied errors.

I'm thinking editing the zip file, somehow changes its rights, but I made sure to give all files execution rights with chmod -R 777 . 
I've added the RUN chmod +x /entrypoint.sh from the readme, but it didn't help.

I work on windows, with version jasperreports-server-cp-6.3.0-bin of the server .

**Comment by sgwood63** [comment]
In the Dockerfile, there are some lines:

	chmod +x /usr/src/jasperreports-server/buildomatic/js-ant && \
	chmod +x /usr/src/jasperreports-server/apache-ant/bin/* && \

Don't know why your permissions would change. One thing to make sure of is the line endings on the .sh scripts to be Unix/Linux (LF) not Windows (CR/LF).

There are 2 ways to get the scheduler settings into the running container.

1) Put your customized scheduler properties files like js.quartz.properties in a zip file with a structure like:
WEB-INF/js.quartz.properties

Have the zip in a volume accessible by Docker and mount it like:

- path_to_volume:/usr/local/share/jasperreports-pro/customization

This will get loaded when the container starts.

2) Change the entrypoint.sh (watch the line endings) at the top:

  cat >/usr/src/jasperreports-server/buildomatic/default_master.properties\
<<-_EOL_
appServerType=tomcat
appServerDir=$CATALINA_HOME
dbType=postgresql
dbHost=$DB_HOST
dbUsername=$DB_USER
dbPassword=$DB_PASSWORD
dbPort=$DB_PORT
js.dbName=$DB_NAME
foodmart.dbName=$FOODMART_DB_NAME
sugarcrm.dbName=$SUGARCRM_DB_NAME
webAppName=jasperserver-pro
maven.jdbc.version=$POSTGRES_JDBC_DRIVER_VERSION
quartz.mail.sender.host=$EMAIL_SERVER
quartz.mail.sender.port=$EMAIL_PORT
quartz.mail.sender.protocol=smtp
quartz.mail.sender.username=$EMAIL_USERNAME
quartz.mail.sender.password=$EMAIL_PASSWORD
quartz.mail.sender.from=$EMAIL_FROM_EMAIL_ADDRESS
quartz.web.deployment.uri=$EMAIL_WEB_DEPLOY_URI
_EOL_


This way, you can set environment variables to control the email config.
