### ISSUE TITLE
Windows Home - Not able install Jaspersoft in docker

### ISSUE THREAD

**Issue by dmaheshwarareddy** [TIBCOSoftware/js-docker#2]
Hi, 

I have tried installation steps as per document however  installation failed with the following error on windows home edition.

Please help me to resolve the issue.

Error Message:
 Service 'jasperserver' failed to build: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/b3/b3e4bba2bff8d24b74175490b02b0edc3a5942edc386228b981ed316ec905a0c/data?Expires=1481615468&Signature=WuKH3kryZ2iS-~hcXYPa9EoTBFalVtHWKD1Xe5UQDh7SQIta5ORnRKpRMmnpWOSegUKataYsnTFy5B65j4JrpzmTeMYo11aG4diM3XT2wyuWX8navKnKNEnQALZ1UNR9skNVsA4vBaCLzSJfGa1gpvaqFxMtFoT7wqPHB5HRDDU_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: read tcp 10.0.2.15:37456->54.230.191.5:443: read: connection reset by peer
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64

please let me know if you need any more info.

Thanks,
Mahesh

**Comment by nataliiakel** [comment]
@dmaheshwarareddy
What Windows version are you running? Are you using Docker for Windows?
Have you made any modifications to the script? What repo DB are you pointing to(external or dockerized)? The list of executed commands would be very helpful to reproduce an issue.

**Comment by sgwood63** [comment]
That looks like the download of the Tomcat/JRE8 image from the Docker Hub failed, which TIBCO Jaspersoft has no control over. Can you try again? Maybe it has been fixed.

Sherman

**Comment by dmaheshwarareddy** [comment]
Hi Sherman,
OS version : Windows 10 Home with Docker toolbox.
not modified script files, executed as it is.
commands used:
docker-compose build
docker-compose up

Thanks,
Mahesh

**Comment by nataliiakel** [comment]
@dmaheshwarareddy Try again. As Sherman pointed out above it looked like tomcat 8 image wasn't getting picked up from the hub.
