### ISSUE TITLE
JasperServer and proxy reverse

### ISSUE THREAD

**Issue by Jaimera** [TIBCOSoftware/js-docker#20]
Im trying to run this JasperServer image under a nginx proxy reverse docker. Everything seens to work great, but CSS, JS and Images cant be loaded. My url for jasper is something like _http://my-sever:4444/env/master/reports/jasperserver_ 

Am I missing something?

Is there a workaround for this problem?

**Comment by nataliiakel** [comment]
@Jaimera  Please, refer to setting proxy definitions in the community article below https://community.jaspersoft.com/wiki/best-practices-deploying-jasperreports-server-your-web-application

**Comment by cyeluri** [comment]
@Jaimera : Are you able to fix your issue? I am also in similar situation and no luck so far.

**Comment by mbochenk** [comment]
Check suggested article. https://community.jaspersoft.com/wiki/best-practices-deploying-jasperreports-server-your-web-application
Most likely you need to set headers in your proxy.
For apache this would be
```
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Port "444"
```
there should be a similar setting for nginx.

**Comment by cyeluri** [comment]
@mbochenk : the suggested wiki is not much helpful in my situation. 

This is how I added NGINX config

   ```
 location ^/v7/jasperserver-pro/ {
        rewrite  (^/v7)(.*) /$2 break;
        proxy_pass http://tibco-jasper;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $host/dcims-jp;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real_IP $remote_addr;
    }
```
