### ISSUE TITLE
SQL Server

### ISSUE THREAD

**Issue by ChaseWhite3** [TIBCOSoftware/js-docker#24]
is it possible that I could get some pointers on how to use this repo to make it compatible with MSSQL Server instead of having PostgreSQL as the default jasperserver repository? Much like this article? https://community.jaspersoft.com/documentation/jasperreports-server-source-build-guide/v561/source-build-setup-other-databases  We have a TIBCO account if that helps any.

**Comment by sgwood63** [comment]
Have a look at the entrypoint.sh. The top of it creates a default_master.properties.
```
  cat >/usr/src/jasperreports-server/buildomatic/default_master.properties\
<<-_EOL_
appServerType=tomcat
appServerDir=$CATALINA_HOME
dbType=postgresql
dbHost=$DB_HOST
dbUsername=$DB_USER
dbPassword=$DB_PASSWORD
dbPort=$DB_PORT
js.dbName=$DB_NAME
foodmart.dbName=$FOODMART_DB_NAME
sugarcrm.dbName=$SUGARCRM_DB_NAME
webAppName=jasperserver-pro
maven.jdbc.version=$POSTGRES_JDBC_DRIVER_VERSION
_EOL_
```

Add your properties for SQL Server there.  And you can use environment variables so values are not hard coded.

**Comment by sgwood63** [comment]
I just committed changes into the master branch that allow a DB_TYPE environment variable to be set for the other databases JasperReports Server supports: MySQL, Microsoft SQL Server, Oracle and DB2.

You can also set a JDBC_DRIVER_VERSION env var to supply your own JDBC driver for those databases via a volume.

Lots of notes in the README.MD. Let us know how that works for you.

Sherman
