### ISSUE TITLE
JAVA_HOME not defined correctly

### ISSUE THREAD

**Issue by jheadley** [TIBCOSoftware/js-docker#25]
I'm trying to run on Docker on Mac and docker-compose build runs fine but _up_ is failing with the error below. It seems to be looking for java in the Jasper install folder on my machine and not running java in the container?

```
Creating js-docker_jasperserver_pro_repository_1 ... done
Creating js-docker_jasperserver-pro_1            ... done
Attaching to js-docker_jasperserver_pro_repository_1, js-docker_jasperserver-pro_1
jasperserver_pro_repository_1  | 2019-06-12 15:25:57.461 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
jasperserver_pro_repository_1  | 2019-06-12 15:25:57.461 UTC [1] LOG:  listening on IPv6 address "::", port 5432
jasperserver-pro_1             | ls: cannot access '/usr/local/tomcat/lib/postgresql-42.2.5.jar': No such file or directory
jasperserver_pro_repository_1  | 2019-06-12 15:25:57.463 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
jasperserver_pro_repository_1  | 2019-06-12 15:25:57.484 UTC [24] LOG:  database system was interrupted; last known up at 2019-06-12 15:00:45 UTC
jasperserver_pro_repository_1  | 2019-06-12 15:25:57.656 UTC [24] LOG:  database system was not properly shut down; automatic recovery in progress
jasperserver_pro_repository_1  | 2019-06-12 15:25:57.658 UTC [24] LOG:  redo starts at 0/1634EA8
jasperserver_pro_repository_1  | 2019-06-12 15:25:57.658 UTC [24] LOG:  invalid record length at 0/1634EE0: wanted 24, got 0
jasperserver_pro_repository_1  | 2019-06-12 15:25:57.658 UTC [24] LOG:  redo done at 0/1634EA8
jasperserver_pro_repository_1  | 2019-06-12 15:25:57.682 UTC [1] LOG:  database system is ready to accept connections
jasperserver-pro_1             | 2019-06-12 15:25:59 URL:https://jdbc.postgresql.org/download/postgresql-42.2.5.jar [825943/825943] -> "/usr/src/jasperreports-server/buildomatic/conf_source/db/postgresql/jdbc/postgresql-42.2.5.jar.1" [1]
jasperserver-pro_1             | ls: cannot access '/usr/local/tomcat/lib/postgresql-42.2.5.jar': No such file or directory
jasperserver-pro_1             | Error: JAVA_HOME is not defined correctly.
jasperserver-pro_1             |   We cannot execute /Users/username/jasperreports-server-7.2.0/java/bin/java
js-docker_jasperserver-pro_1 exited with code 1
```

**Comment by sgwood63** [comment]
I don't understand how that is happening.
The OpenJDK Java being executed should be in the jasperserver-pro image you built.
It comes in with the *FROM tomcat:9.0-jre8* in the Dockerfile.

I don't know why the entrypoint.sh would be trying to access /Users/username/jasperreports-server-7.2.0/java/bin/java, which looks like it is on your Mac, not in the image.

I have tested this on Linux and Docker for WIndows. Maybe a Docker for Mac peculiarity?

Did you change any volumes in the docker-compose?

**Comment by jheadley** [comment]
No I'm trying straight out of git, unmodified. A colleague tried linux and got the same error. That path isn't even the JAVA_HOME that's set on my machine. That's where I had the jasper install place the files that were later used to build the war needed for the docker container and tomcat. Is the war generator process grabbing that path for some reason? I've tried setting JAVA_HOME to different values in both the dockerfile and docker-compose.yml and path in the error never changes.

**Comment by sgwood63** [comment]
Attached is an entrypoint.sh that prints the Java environment and version which are in the image.

Could you add these commands into the entrypoint.sh just before the final case statement?

echo "Check JAVA environment"
env | grep JAVA
java -version
echo $PATH
whereis java


I am getting:

Check JAVA environment variables
JAVA_OPTS=-XX:MaxMetaspaceSize=378m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
JAVA_HOME=/docker-java-home/jre
JAVA_VERSION=8u212
JAVA_DEBIAN_VERSION=8u212-b01-1~deb9u1
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
/usr/local/tomcat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
java: /usr/bin/java /usr/share/java /usr/share/man/man1/java.1.gz

**Comment by jheadley** [comment]
I get the same results but that does not appear to be the java that jasper is attempting to use. 

```
Creating js-docker_jasperserver_pro_repository_1 ... done
Creating js-docker_jasperserver-pro_1            ... done
Attaching to js-docker_jasperserver_pro_repository_1, js-docker_jasperserver-pro_1
jasperserver_pro_repository_1  | 2019-06-14 20:01:05.853 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
jasperserver_pro_repository_1  | 2019-06-14 20:01:05.853 UTC [1] LOG:  listening on IPv6 address "::", port 5432
jasperserver-pro_1             | Check JAVA environment
jasperserver_pro_repository_1  | 2019-06-14 20:01:05.855 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
jasperserver-pro_1             | JAVA_OPTS=-XX:MaxMetaspaceSize=378m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
jasperserver-pro_1             | JAVA_HOME=/docker-java-home/jre
jasperserver-pro_1             | JAVA_VERSION=8u212
jasperserver-pro_1             | JAVA_DEBIAN_VERSION=8u212-b01-1~deb9u1
jasperserver_pro_repository_1  | 2019-06-14 20:01:05.870 UTC [24] LOG:  database system was interrupted; last known up at 2019-06-12 19:54:32 UTC
jasperserver_pro_repository_1  | 2019-06-14 20:01:05.996 UTC [24] LOG:  database system was not properly shut down; automatic recovery in progress
jasperserver_pro_repository_1  | 2019-06-14 20:01:05.998 UTC [24] LOG:  redo starts at 0/1635420
jasperserver_pro_repository_1  | 2019-06-14 20:01:05.998 UTC [24] LOG:  invalid record length at 0/1635458: wanted 24, got 0
jasperserver_pro_repository_1  | 2019-06-14 20:01:05.998 UTC [24] LOG:  redo done at 0/1635420
jasperserver_pro_repository_1  | 2019-06-14 20:01:06.012 UTC [1] LOG:  database system is ready to accept connections
jasperserver-pro_1             | openjdk version "1.8.0_212"
jasperserver-pro_1             | OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
jasperserver-pro_1             | OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
jasperserver-pro_1             | /usr/local/tomcat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
jasperserver-pro_1             | java: /usr/bin/java /usr/share/java /usr/share/man/man1/java.1.gz
jasperserver-pro_1             | ls: cannot access '/usr/local/tomcat/lib/postgresql-42.2.5.jar': No such file or directory
jasperserver-pro_1             | 2019-06-14 20:01:07 URL:https://jdbc.postgresql.org/download/postgresql-42.2.5.jar [825943/825943] -> "/usr/src/jasperreports-server/buildomatic/conf_source/db/postgresql/jdbc/postgresql-42.2.5.jar.1" [1]
jasperserver-pro_1             | ls: cannot access '/usr/local/tomcat/lib/postgresql-42.2.5.jar': No such file or directory
jasperserver-pro_1             | Error: JAVA_HOME is not defined correctly.
jasperserver-pro_1             |   We cannot execute /Users/<my username>/jasperreports-server-7.2.0/java/bin/java
js-docker_jasperserver-pro_1 exited with code 1
```

**Comment by sgwood63** [comment]
The point where the exception is happening is running Ant scripts that use Java, not the js-import-export.sh. Though  js-import-export.sh is used later, so the same issue would occur the the entrypoint gets there.

Does the zip file you had in the resources directory include Java? It should not.
The zip must be a JasperReports Server "WAR File Installer".
It cannot be purely a zip of where you did a "bundled install".
As noted in the js-docker README, you can build a WAR File installer using this process:
[Jaspersoft community wiki article](https://community.jaspersoft.com/wiki/creating-jasperreports-server-war-file-installer-bundled-installer)

Hmmm... maybe you used that "build a WAR File installer" process and the Mac bundled installer makes changes to the shell scripts that I am not expecting? Are there other places in what you zipped that set values to /Users/<my username>/jasperreports-server-7.2.0/java/bin/java?
Can you do a global search of the zip contents to see whether there are other references to "/Users/<my username>"?

**Comment by jheadley** [comment]
Yes I used that wiki article to make the war. I unzipped what that process created and searched for /Users/ in the contents.

**buildomatic/build_conf/default/js-mvn/app.srv.properties**
line 35 in the asadminPath

**buildomatic/build_conf/default/js-mvn and buildomatic/js-mvn**
line 15 in $MVN_RUN as well as lines 20 and 21 in some echo statements

**buildomatic/build_conf/default/maven_settings_mirror.xml**
lines 24, 32,33,35,40,41,42,43

**buildomatic/build_conf/default/maven_settings.xml**
lines 24, 32,33,35,40,41,42,43

**Comment by sgwood63** [comment]
I have had other folks using this Dockerfile and the WAR file installer with no problems.
I have seen some funkiness with Docker for Mac where the build failed and left the intermediate containers in a bad state.

Could you delete the jasperserver-pro:7.2.0 image, rebuild and try again?

Thanks,

Sherman

**Comment by jheadley** [comment]
Seems the same. I did a pull to get the commit from a few days ago and tried that too.

```
Attaching to js-docker_jasperserver_pro_repository_1, js-docker_jasperserver-pro_1
jasperserver_pro_repository_1  | 2019-06-18 17:22:31.861 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
jasperserver_pro_repository_1  | 2019-06-18 17:22:31.861 UTC [1] LOG:  listening on IPv6 address "::", port 5432
jasperserver_pro_repository_1  | 2019-06-18 17:22:31.864 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
jasperserver_pro_repository_1  | 2019-06-18 17:22:31.879 UTC [24] LOG:  database system was shut down at 2019-06-14 21:04:36 UTC
jasperserver-pro_1             | ##### Failing! ##### Saw 0 OK connections, not at least 1
jasperserver-pro_1             | Sleeping to try postgresql at host jasperserver_pro_repository connection again...
jasperserver_pro_repository_1  | 2019-06-18 17:22:31.890 UTC [1] LOG:  database system is ready to accept connections
jasperserver-pro_1             | Error: JAVA_HOME is not defined correctly.
jasperserver-pro_1             | We cannot execute /Users/headley/jasperreports-server-7.2.0/java/bin/java
jasperserver-pro_1             | ##### Failing! ##### Saw 0 OK connections, not at least 1
jasperserver-pro_1             | Sleeping to try postgresql at host jasperserver_pro_repository connection again...
jasperserver-pro_1             | Error: JAVA_HOME is not defined correctly.
jasperserver-pro_1             | We cannot execute /Users/<my username>/jasperreports-server-7.2.0/java/bin/java
jasperserver-pro_1             | ##### Failing! ##### Saw 0 OK connections, not at least 1
jasperserver-pro_1             | Sleeping to try postgresql at host jasperserver_pro_repository connection again...
jasperserver-pro_1             | Error: JAVA_HOME is not defined correctly.
jasperserver-pro_1             | We cannot execute /Users/<my username>/jasperreports-server-7.2.0/java/bin/java
jasperserver-pro_1             | ##### Failing! ##### Saw 0 OK connections, not at least 1
jasperserver-pro_1             | Sleeping to try postgresql at host jasperserver_pro_repository connection again...
jasperserver-pro_1             | Error: JAVA_HOME is not defined correctly.
jasperserver-pro_1             | We cannot execute /Users/<my username>/jasperreports-server-7.2.0/java/bin/java
jasperserver-pro_1             | ##### Failing! ##### Saw 0 OK connections, not at least 1
jasperserver-pro_1             | postgresql at host jasperserver_pro_repository not accessible or cannot log in!
jasperserver-pro_1             | ##### Exiting #####
js-docker_jasperserver-pro_1 exited with code 1
```

**Comment by sgwood63** [comment]
I have seen this issue with another customer. It appears to be related to the WAR file installer creation script under Linux - using the official WAR file installer is fine, and the WAR file installer creation script with Windows and Mac work too. Will test and fix.

Sherman

**Comment by sgwood63** [comment]
I found the problem, which was specific to using the build-WAR-file-installer process on Linux. The fix required changes in both the build-WAR-file-installer and the Dockerfile.

So pull down the latest zip file from https://community.jaspersoft.com/wiki/creating-jasperreports-server-war-file-installer-bundled-installer
and use the build-WAR-file-installer.sh to build your TIB_js-jrs_7.2.0_bin.zip.

Get the latest from this repository https://github.com/TIBCOSoftware/js-docker

docker build -t jasperserver-pro:7.2.0 .

Will leave this issue open for feedback for a few days.

Sherman

**Comment by jheadley** [comment]
Thanks Sherman. That seems to have fixed it. I appreciate all the help. 

Jeff
