### ISSUE TITLE
Property Settings for RDS/SSL connection for JasperDB

### ISSUE THREAD

**Issue by rjackson-dev-ops** [TIBCOSoftware/js-docker#27]
We're trying to figure out how to connect via SSL to our AWS RDS JasperDB. Currently we are using a property file like this one with "buildomatic."

  cat >/usr/src/jasperreports-server/buildomatic/default_master.properties\
<<-_EOL_
appServerType=tomcat8
appServerDir=$CATALINA_HOME
dbType=postgresql
dbHost=$DB_HOST
dbUsername=$DB_USER
dbPassword=$DB_PASSWORD
dbPort=$DB_PORT
js.dbName=$DB_NAME
_EOL_

We need it to build a jdbc url like this:

jdbc:postgresql://jasperserver.amazon.com:5432/jasper_db?ssl=true&sslmode=verify-full&sslrootcert=/opt/rds-combined-ca-bundle-from-aws.pem&sslcert=/opt/rds-combined-ca-bundle-from-aws.pem

**Comment by sgwood63** [comment]
Given this JasperReports Server container build relies on Jaspersoft "buildomatic", the generation of the repository JDBC connection is difficult to change.

The workaround here is to load a META-INF/context.xml as a customization. Customizations are loaded after the META-INF/context.xml is updated by buildomatic.

**Comment by rjackson-dev-ops** [comment]
Thanks for the information. I ended up just modifying the db.template.properties file.

# jdbc url templates...assume same host, port, db type
admin.jdbcUrl=jdbc:postgresql://${dbHost}:${dbPort}/postgres?ssl=true&amp;sslmode=verify-full&amp;sslrootcert=/opt/rds-combined-ca-bundle-from-aws.pem&amp;sslcert=/opt/rds-combined-ca-bundle-from-aws.pem
js.jdbcUrl=jdbc:postgresql://${dbHost}:${dbPort}/${js.dbName}?ssl=true&amp;sslmode=verify-full&amp;sslrootcert=/opt/rds-combined-ca-bundle-from-aws.pem&amp;sslcert=/opt/rds-combined-ca-bundle-from-aws.pem
js.it.jdbcUrl=jdbc:postgresql://${dbHost}:${dbPort}/${js.it.dbName}?ssl=true&amp;sslmode=verify-full&amp;sslrootcert=/opt/rds-combined-ca-bundle-from-aws.pem&amp;sslcert=/opt/rds-combined-ca-bundle-from-aws.pem
sugarcrm.jdbcUrl=jdbc:postgresql://${dbHost}:${dbPort}/${sugarcrm.dbName}?ssl=true&amp;sslmode=verify-full&amp;sslrootcert=/opt/rds-combined-ca-bundle-from-aws.pem&amp;sslcert=/opt/rds-combined-ca-bundle-from-aws.pem
foodmart.jdbcUrl=jdbc:postgresql://${dbHost}:${dbPort}/${foodmart.dbName}?ssl=true&amp;sslmode=verify-full&amp;sslrootcert=/opt/rds-combined-ca-bundle-from-aws.pem&amp;sslcert=/opt/rds-combined-ca-bundle-from-aws.pem

**Comment by sgwood63** [comment]
Oh, very cool!
Does setting these properties in the default_master.properties work? If so, you could put them in a default_master.properties customization loaded via the entrypoint.sh and not have to change the image.
