### ISSUE TITLE
Non-working Jaspersoft WAR File Installer builder

### ISSUE THREAD

**Issue by danielfcastro** [TIBCOSoftware/js-docker#28]
1 - I read the page https://github.com/TIBCOSoftware/js-docker
2 - On section Get the JasperReports Server WAR file installer I change dir to the downloaded git reprository and navigate until buildWARFileInstaller
3 - I run build-WAR-file-installer.bat
4 - In a first moment the bat returns error.

I begun searching for the cause.
The first problem is due the fact that the folder buildomatic and apache-ant are inside the folder additionalResources and they are referenced inside build-WAR-file-installer.bat as if they were in the same level as additionalResources.

The second problem is in buildWARFileInstaller.xml.  It references <taskdef resource="net/sf/antcontrib/antlib.xml"/> but the ant-contrib.jar file is not referenced anywhere in documentation nor downloaded with the repository git.  So you must download it and replace line 4 of the xml for this

    <taskdef resource="net/sf/antcontrib/antlib.xml">
		<classpath>
			<pathelement location="C:/ant/ant-contrib/ant-contrib-1.0b3.jar"/>
		</classpath>	
	</taskdef>

After that you reexecute and the bat files complains about apache-tomcat\webapps\jasperserver-pro that does not exists.

After I created the file it generates a zip file 
[zip] Building zip: C:\Openshift Command Line\js-docker\buildWARFileInstaller\TIB_js-jrs_undefined_bin.zip
with only the ant files inside.

Quiet frustrating...

**Comment by sgwood63** [comment]
Hi Daniel,

The instructions for the WAR File installer builder are here: https://github.com/TIBCOSoftware/js-docker/tree/master/buildWARFileInstaller (README.MD)

It looks like you did not copy the buildWARFileInstaller files into the JasperReports Server installation directory and run the script from there.
