### ISSUE TITLE
deployment broken with default (latest Tomcat) available

### ISSUE THREAD

**Issue by dnaboka** [TIBCOSoftware/js-docker#29]
JasperServer 7.2.0 doesn't run on Tomcat 9.0.29. We only certify Tomcat 9.0.17:
https://community.jaspersoft.com/wiki/tomcat-will-not-deploy-jasperserver-tenantbean-already-exists-error

**Comment by sgwood63** [comment]
Added TOMCAT_BASE_IMAGE build time ARG to Dockerfile to set the version of Tomcat we are going to FROM from.
Default is "tomcat:9.0.17-jre8" which certified for JasperReports Server 7.2.0.
