### ISSUE TITLE
clarification on running 7.5 CE 

### ISSUE THREAD

**Issue by phinnay** [TIBCOSoftware/js-docker#30]
Unsure how to adapt the scripts in this repo to work with 7.5 CE. All references in entrypoint.sh point to jasperserver-pro and I am unable to generate keystore properly.

**Comment by sgwood63** [comment]
We are only going to develop for and test the commercial deployments of JasperReports Server in containers in this repository.

Bitnami has excellent container deployment of JasperReports Server Community edition, including https://github.com/helm/charts/tree/master/stable/jasperreports

**Comment by phinnay** [comment]
Ok that makes total sense, would it be possible to get some mention of that in the README? I see I'm not the only one who's made the assumption and it'd be a time saver on both sides. 

Thank you for a wonderful product :D
