### ISSUE TITLE
JasperServer internal server error with stacktrace

### ISSUE THREAD

**Issue by Zeebrow** [TIBCOSoftware/js-docker#31]
[jre-docker-stacktrace02-10-20.txt](https://github.com/TIBCOSoftware/js-docker/files/4182667/jre-docker-stacktrace02-10-20.txt)

**Comment by sgwood63** [comment]
This failure comes from:

- the JasperReports Server repository database exists in Postgresql
- database has the JasperReports Server tables in that database
- database does not contain the "minimal-pro" import in the tables

What is specifically missing is the organization_1 tenant, which is required.

Please import minimal-pro through the command line.
