### ISSUE TITLE
jsdocker_jasperserver_1 exited with code 1 default_master.properties not found

### ISSUE THREAD

**Issue by bor1e** [TIBCOSoftware/js-docker#4]
Hello,

I have a freshly installed docker & docker-compose and followed the steps from the README.md file.
 
After running `docker-compose build` which couldn't execute the following prompt `mv /usr/src/jasperreports-server-*` [Dockerfile:14] I changed it to `mv /usr/src/JasperReports-Server-*` (with capital letters) it worked for me.

But when I ran `docker-compose up ` I've received the following output:
```
js_database_1   | LOG:  MultiXact member wraparound protections are now enabled
js_database_1   | LOG:  database system is ready to accept connections
js_database_1   | LOG:  autovacuum launcher started
jasperserver_1  | /entrypoint.sh: line 29: /usr/src/jasperreports-server/buildomatic/default_master.properties: No such file or directory
jsdocker_jasperserver_1 exited with code 1
```

I did no further changes in the files. Any Ideas where how to resolve that one?

Best regards

**Comment by ernestoongaro** [comment]
Hello @bor1e thanks for trying this out! I guess when you unzipped the war file the folder name is JasperReports-Server - could you rename it to lowercase to see if it works (instead of fixing the script, fix the file?)

Also, what operating system and version of jaspersoft are you using?

**Comment by bor1e** [comment]
I didn't unzip the war file. I just copied it to the resources folder of the js-docker. It war from the beginning in lower case. This is the file-name `jasperreports-server-6.3.0-src.zip`. I thought that docker is building out of it a war file. 

I use Ubuntu 16.04 xenial, JasperSoft version 6.3.0 the pro version.

**Comment by ernestoongaro** [comment]
Ah ok! It should be the WAR file that you use, not the src - so the file should be jasperreports-server-6.3.0-bin

**Comment by ernestoongaro** [comment]
@bor1e - did that fix the problem for you?

**Comment by nataliiakel** [comment]
@bor1e I will close the issue. IF you still see an issue, please feel free to reopen.
