### ISSUE TITLE
Latest community download is jasperserver.war not jasperserver-pro.war

### ISSUE THREAD

**Issue by ArcticSnowman** [TIBCOSoftware/js-docker#6]
Latest community download is jasperserver.war not jasperserver-pro.war

entrypoint.sh assumes the later and fails to run...

**Comment by ernestoongaro** [comment]
Hi @ArcticSnowman - there are a few differences in the names of the scripts as well, i have a special version of entrypoint.sh that works only with the community edition here: https://gist.github.com/ernestoongaro/64d8a6244251fb1dc41408d54ee803dd - I just tested with 6.3 CE and all went well. 

Will talk to maintainers to get this included in next release.

**Comment by ArcticSnowman** [comment]
Cool, Thanks..   I'll give it a try.

**Comment by ArcticSnowman** [comment]
I've setup a fork of this code base to include some other changes..   Dockerfile and docker-compose.yml need tweeks to change `jasperserver-pro` to `jasperserver`.

One issue I'm hitting is that due to network constraints I'm running the tomcat behind a nginx proxy, which is handling the SSL termination.  This seems to cause TomCat issues. 

```
jasperserver_1  | 2017-05-02 17:52:39,857 ERROR CsrfGuard,http-apr-8080-exec-10:44 - Referer domain https://dev-jasper.grantstreet.com/jasperserver/login.html does not match request domain: http://dev-jasper.grantstreet.com/jasperserver/JavaScriptServlet
```

 I'm not sure how to fix that...

**Comment by tstrypko** [comment]
Gentlemen, are symptoms of the problem you're discussing something like the following?
```
jasperserver_1  | deploy-webapp:
jasperserver_1  |      [echo] For JDBC driver the artifactId and version properties are set:
jasperserver_1  |      [echo]   maven.jdbc.artifactId=postgresql
jasperserver_1  |      [echo]   maven.jdbc.version=9.2-1002.jdbc4
jasperserver_1  |      [echo]   Specified JDBC driver jar exists
jasperserver_1  |      [echo] About to copy JDBC driver for import-export config (if it exists):
jasperserver_1  |    [delete] Deleting directory /usr/local/tomcat/webapps/jasperserver-pro
jasperserver_1  |
jasperserver_1  | BUILD FAILED
jasperserver_1  | /usr/src/jasperreports-server/buildomatic/bin/app-server.xml:745: Unable to delete directory /usr/local/tomcat/webapps/jasperserver-pro
jasperserver_1  |
jasperserver_1  | Total time: 1 second
mytest_jasperserver_1 exited with code 1
```
Tried @ernestoongaro's **entrypoing.sh**, but it gives me this:

```
jasperserver_1  | Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar
jasperserver_1  | Buildfile: /usr/src/jasperreports-server/buildomatic/build.xml
jasperserver_1  |      [echo] Filtering properties (cleaning out blank spaces)
mytest_jasperserver_1 exited with code 137
```.

Used *jasperreports-server-cp-6.3.0-bin.zip*. Any clue what's up?

**Comment by tstrypko** [comment]
Eventually fixed problems. Not sure what made the difference, but here some points:

1. Used @ernestoongaro entrypoint.sh
2. Although, had to start it with #!/bin/bash, otherwise it complained on [[ operator.

**Comment by ernestoongaro** [comment]
Hi @tstrypko - thanks for the heads up.

**Comment by nataliiakel** [comment]
@ArcticSnowman the repo is intended to be used with JasperReports Server Professional edition.
