### ISSUE TITLE
No way to configure at runtime

### ISSUE THREAD

**Issue by yoda** [TIBCOSoftware/js-docker#75]
Is there anyway to configure username, password, database, hostname via k8s at runtime. Doesnt seem to be anyway to use the helm chart to mount default_master.properties to override, due to the buildomatic not using the volume imports. Is the only way to configure the image at build time?

**Comment by rreddyv-tibco** [comment]
for now it is only the way to configure the database credentials . You can get that feature in subsequent releases 

Thanks,

**Comment by yoda** [comment]
This might be useful for reference

https://github.com/bitnami/bitnami-docker-jasperreports
