### ISSUE TITLE
Compatibility with commercial version

### ISSUE THREAD

**Issue by tstrypko** [TIBCOSoftware/js-docker#8]
Is it possible to use these scripts to build a Docker image of PRO JasperServer version?

If so, where do i get a **jasperreports-server-*.zip** file? My company owns 5.6.0 PRO license.

**Comment by ernestoongaro** [comment]
@tstrypko - this project is ONLY compatible with the Pro edition, you can get the WAR file from https://edelivery.tibco.com

**Comment by ernestoongaro** [comment]
@nataliiakel  - can you close this issue? @tstrypko if you have a question about this please email me e - o - n - g - a - r - o - @ - t - i - b - c - o - . - c - o - m

**Comment by nataliiakel** [comment]
@tstrypko I will close the issue. Please, contact Ernesto if needed more information.
