### ISSUE TITLE
Problem with jasperreports on aws ec2

### ISSUE THREAD

**Issue by LuisJoseLopezD** [TIBCOSoftware/js-docker#90]
This is my security group, i have also allowed all my ports on my ubuntu server and i disabled the ufw, any suggestions?
![server](https://github.com/TIBCOSoftware/js-docker/assets/45377927/470e8366-436d-4f50-9a47-c1265ee89a7c)
![security-group](https://github.com/TIBCOSoftware/js-docker/assets/45377927/2f3c730d-eb2d-4c21-b07d-43f3a837d7f1)

**Comment by LuisJoseLopezD** [comment]
And i always get this message from the browser: The connection has been rejected

**Comment by mbochenk** [comment]
I am not sure what are you doing here. 
Is it CE or PRO edition? If you are using pro, this should be jasperserver-pro.
Have you used helm chart to deploy? 
Why are you using 8443 port - did you set up certificate for it? Are you using https for url or is it trying http over 8443?
If you set up LB, you usually want to use https on default 443

**Comment by LuisJoseLopezD** [comment]
> I am not sure what are you doing here. Is it CE or PRO edition? If you are using pro, this should be jasperserver-pro. Have you used helm chart to deploy? Why are you using 8443 port - did you set up certificate for it? Are you using https for url or is it trying http over 8443? If you set up LB, you usually want to use https on default 443

I am not using jasperserver-pro, i don't have any certificate for this. This is tottaly the CE.

![image](https://github.com/TIBCOSoftware/js-docker/assets/45377927/e746aae6-50f4-40df-af79-0dbaa547cc86)
Those are my files, and my images are running, they called jasper and jasperdb.

I just want to start the server to enter this url: https://YOUR_HOSTNAME:8443/jasperserver

Any idea? thank you!

**Comment by himanshu3663** [comment]
Hi Luis,

Please note that this js-docker repository is meant to be working out of the box with Jasper Server Pro artifacts. However, you could tweak the docker files to make it work with Jasper Server CE. Additionally, you may want to try using the docker images created by Bitnami: https://hub.docker.com/r/bitnami/jasperreports/.

Also, by default, the server runs on http so you may want to try using the url like http://{HOSTNAME}:8080/jasperserver

**Comment by LuisJoseLopezD** [comment]
> Hi Luis,
> 
> Please note that this js-docker repository is meant to be working out of the box with Jasper Server Pro artifacts. However, you could tweak the docker files to make it work with Jasper Server CE. Additionally, you may want to try using the docker images created by Bitnami: https://hub.docker.com/r/bitnami/jasperreports/.
> 
> Also, by default, the server runs on http so you may want to try using the url like http://{HOSTNAME}:8080/jasperserver

i am using dockers images created by bitnami, my question is why does not work with the aws ec2 server? there is any config about the ports that don't allow me to init the server in the security groups?

**Comment by himanshu3663** [comment]
For Jasper Server Pro deployed using the js-docker scripts, there are no other requirements on configuring security groups. I think you should reach out to Bitnami support for this issue.
